### PR TITLE
Pipeline for testing based on cirros

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Minor tweaks to make the pipeline work with `kubevirtci` clusters and an example based on cirros which can also be used as presubmit entrypoint.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
I think we don't need the extra `--cluster-registry` as medius itself does not use the registry in `images verify`. `--registry` is only used to construct the imgRef which is passed to the cluster. Other than that LGTM.

**Comment by rmohr** [comment]
> I think we don't need the extra `--cluster-registry` as medius itself does not use the registry in `images verify`. `--registry` is only used to construct the imgRef which is passed to the cluster. Other than that LGTM.

:+1: Misunderstood it. Fixed.

**Pull request merged**
