### PR TITLE
docs: add setup local registry

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

To run local testing of Medius,
developer will need to setup
a local container registry.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Please frame it as a light alternative for **just** building images. The default workflow for all of the available commands should remain using kubevirtci.

**Comment by codingben** [comment]
> Please frame it as a light alternative for **just** building images. The default workflow for all of the available commands should remain using kubevirtci.

I disagree. Promote command can be also used to publish from source (e.g. local registry) to target registry (e.g. Quay.io) - KubeVirt CI isn't needed here as well.

By the way, currently there is `--target-registry=localhost:49501` - Does it assume that this is KubeVirt CI registry or it's just random ${IP}:${PORT}?

**Comment by 0xFelix** [comment]
Indeed, it assumes a kubevirtci registry. You can extend the documentation to make it clear. Still, for local testing of the full chain of commands a kubevirtci cluster should be preferred.

**Comment by codingben** [comment]
@0xFelix I've added `... to just build and publish`. Can you please review it?

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
