### PR TITLE
chore: Bump dependencies and golanglint-ci

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Bump dependencies and golanglint-ci

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by jcanocan — COMMENTED** [review]
Thanks for taking care of this.
I see some deps are being downgraded. For instance:

```diff
- github.com/gorilla/websocket v1.5.3 // indirect
+ github.com/gorilla/websocket v1.5.0 // indirect
```
Do we know why?

**Comment by 0xFelix** [comment]
Needs https://github.com/kubevirt/project-infra/pull/3591 first

**Pull request merged**
