### PR TITLE
registry: Remove CentOS 8.4 and Ubuntu 18.04

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

Both are now EOL and should no longer be sync'd.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
IMO it is fine to drop the build of these artifacts. The latest artifacts will remain on quay, until they are deleted manually.

**Comment by codingben** [comment]
I think we have now conflicts because https://github.com/kubevirt/containerdisks/pull/93 was merged earlier.

**Review by 0xFelix — APPROVED** [review]
/approve

Thanks!

**Pull request merged**
