### PR TITLE
chore: Drop rhcos and rhcosprerelease containerdisks

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Drop the rhcos and rhcosprerelease containerdisks, since they are not used anymore.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by dominikholler** [comment]
@0xFelix Thank you!

**Comment by 0xFelix** [comment]
https://github.com/kubevirt/project-infra/pull/3222 needs to be merged to drop the no longer required test lane.

**Pull request merged**
