### PR TITLE
Add s390x support for Fedora artifact

### PR DESCRIPTION
**Pull request by aditi-sharma-1**
This pull request adds s390x architecture support for the Fedora artifact in the Containerdisks repository. These changes ensure compatibility, enabling support for s390x alongside existing platforms.

**Release note**:

```release-note
Add s390x artifact
```
Signed-off-by: Aditi Sharma [Aditi.Sharma@ibm.com](mailto:Aditi.Sharma@ibm.com)

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Looks good to me. Not sure the `nil` assignments to `EnvVariables` should be dropped for now.

/test all

**Comment by aditi-sharma-1** [comment]
> Looks good to me. Not sure the `nil` assignments to `EnvVariables` should be dropped for now.
> 
> /test all

Hi @0xFelix,

Thank you for the review! The nil assignments to the EnvVariables are working well and have not caused any issues on s390x. We also used this locally built Fedora image for downstream OCP-Virt tier-0 local testing, and it was successful.

Please let me know your thoughts. Thank you!

**Review by 0xFelix — COMMENTED** [review]
@aditi-sharma-1 Right, that was from a code style perspective. But I suppose you will update this soon once the common-instancetypes for s390x are out?

/approve

**Pull request merged**
