### PR TITLE
Add ArtifactsGatherer interface and implementation for Fedora Linux

### LINKED ISSUE #35: Add all fedora versions
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

A manual PR, e.g. https://github.com/kubevirt/containerdisks/pull/33  to add the latest fedora version was required.

**What you expected to happen**:

The new fedora version is added automatically, e.g. from https://getfedora.org/releases.json .

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This interface allows to dynamically populate common.Registry by
gathering artifacts of a distribution during runtime. An
ArtifactsGatherer for Fedora Linux is implemented as reference.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #35 

**Special notes for your reviewer**:

Merge after #36 

**Release note**:

```release-note
Dynamically gather releases of Fedora Linux
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
@davidvossel Could you have a look at this, please?

**Comment by lyarwood** [comment]
@0xFelix  Can you drop commit [9c22e55](https://github.com/kubevirt/containerdisks/pull/37/commits/9c22e559c2f836e6ff25aa6256af651ee1818878) from this PR if you're going to land it in https://github.com/kubevirt/containerdisks/pull/36 separately?

**Comment by lyarwood** [comment]
> @0xFelix Can you drop commit [9c22e55](https://github.com/kubevirt/containerdisks/pull/37/commits/9c22e559c2f836e6ff25aa6256af651ee1818878) from this PR if you're going to land it in #36 separately?

Apologies I missed it's actually used here so you have to pull it in, github--

/assign lyarwood

**Comment by lyarwood** [comment]
LGTM thanks @0xFelix ! /approve

**Pull request merged**
