### PR TITLE
Add UseForLatest attribute to common.Registry entries

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This attribute allows to specify if the artifact of the entry should
be additionally tagged with ':latest'.

**Release note**:

```release-note
Add UseForLatest attribute to common.Registry entries
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
@davidvossel Could you have a look at this, please?

**Comment by lyarwood** [comment]
> @davidvossel Could you have a look at this, please?

Ah apologies it's used in 022bd3d761c13b3ad9a8a2619b9aa2243b801c05, lets land it first and then review this.

**Review by davidvossel — APPROVED** [review]
/approve

**Pull request merged**
