### PR TITLE
CentOS 7 and CentOS Stream 8 EOL

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
CentOS 7 and CentOS Stream 8 containerdisks are no longer maintained by the project
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
/approve

Should we mark them as deprecated on quay too?

**Comment by lyarwood** [comment]
> /approve
> 
> Should we mark them as deprecated on quay too?

@0xFelix I guess that would require manually editing the documentation in the repo at this stage right? Would you be okay doing that, adding a deprecation notice and highlighting that the disks will eventually be removed in the future?

**Comment by 0xFelix** [comment]
@lyarwood To mark CentOS Stream 8 as deprecated on quay an update to the artifacts description is required because Stream 8 and 9 live in the same quay repository and manual edits would be overridden on the next push.

https://github.com/kubevirt/containerdisks/blob/5796ff616da0932ccba9ed9321980f3e500329b6/artifacts/centosstream/centos-stream.go#L20

**Comment by lyarwood** [comment]
> @lyarwood To mark CentOS Stream 8 as deprecated on quay an update to the artifacts description is required because Stream 8 and 9 live in the same quay repository and manual edits would be overridden on the next push.
> 
> https://github.com/kubevirt/containerdisks/blob/5796ff616da0932ccba9ed9321980f3e500329b6/artifacts/centosstream/centos-stream.go#L20

Added https://github.com/kubevirt/containerdisks/pull/148/commits/aa1e66032191bf6004a2c8279a1974a9c27d1109

**Comment by 0xFelix** [comment]
@lyarwood Can you open a PR to remove the `pull-containerdisks-pipeline-centos` before this is merged? Thank you!

**Comment by lyarwood** [comment]
> @lyarwood Can you open a PR to remove the `pull-containerdisks-pipeline-centos` before this is merged? Thank you!

https://github.com/kubevirt/project-infra/pull/3507

@0xFelix  Done.

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by 0xFelix** [comment]
Updated the description on https://quay.io/repository/containerdisks/centos and created https://github.com/kubevirt/containerdisks/issues/154.

**Pull request merged**
